name: simply_bills_manager
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.6
  flutter:
    sdk: flutter
  get: 4.6.6
  google_fonts: ^6.2.1
  serverpod_auth_email_flutter: 2.0.2
  serverpod_auth_shared_flutter: 2.0.2
  serverpod_chat_flutter: 2.0.2
  serverpod_flutter: 2.0.2
  simply_bills_client:
    path: ../simply_bills_client

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
